#include "../src/akdf.hpp"
#include <iostream>
#include <stdexcept>
using namespace tuntom;
void require(bool ok, const char* why) { if (!ok) throw std::runtime_error(why); }
int main() {
    ascon::key_type psk {}, prk {}, expected {}, c2s {}, s2c {}, hint {}, changed {};
    std::array<std::uint8_t, 32> dh {};
    for (std::size_t i = 0; i < psk.size(); ++i) psk[i] = static_cast<std::uint8_t>(i);
    for (std::size_t i = 0; i < dh.size(); ++i) dh[i] = static_cast<std::uint8_t>(32 + i);
    const std::string extract_label("TUNTOM-AKDF-v1-EXTRACT\0", 23);
    std::vector<std::uint8_t> input(extract_label.begin(), extract_label.end());
    input.insert(input.end(), dh.begin(), dh.end());
    ascon::mac(psk, 42, input.data(), input.size(), expected);
    akdf::extract(prk, psk, 42, dh);
    require(prk == expected, "extract framing");
    const std::vector<std::uint8_t> transcript {0, 1, 2, 255};
    akdf::expand(c2s, prk, 42, "TUNTOM-AKDF-v1-C2S", transcript);
    akdf::expand(s2c, prk, 42, "TUNTOM-AKDF-v1-S2C", transcript);
    akdf::expand(hint, prk, 42, "TUNTOM-AKDF-v1-HINT", transcript);
    const std::string expand_label("TUNTOM-AKDF-v1-C2S\0", 19);
    input.assign(expand_label.begin(), expand_label.end());
    input.insert(input.end(), {0, 0, 0, 0, 0, 0, 0, 4, 0, 1, 2, 255, 1});
    ascon::mac(prk, 42, input.data(), input.size(), expected);
    require(c2s == expected, "expand framing");
    // Fixed regression vectors generated by independent lookup-S-box Python code.
    auto matches = [](const ascon::key_type& bytes, const char* hex) {
        for (std::size_t i = 0; i < bytes.size(); ++i)
            if (bytes[i] != std::stoul(std::string(hex + i*2, 2), nullptr, 16)) return false;
        return true;
    };
    require(matches(prk, "9918fbc76d8a36087c9d4adb33d80ed9"), "PRK KAT");
    require(matches(c2s, "d665fb496abc0d32716b716afd690388"), "C2S KAT");
    require(matches(s2c, "f2edcdf874d30a54816c9daec844f7ae"), "S2C KAT");
    require(matches(hint, "47d51288b8455b2f72bd1a2375ade0b2"), "hint KAT");
    require(c2s != s2c && c2s != hint && s2c != hint, "domain separation");
    auto different = transcript; different.push_back(0);
    akdf::expand(changed, prk, 42, "TUNTOM-AKDF-v1-C2S", different);
    require(changed != c2s, "transcript length binding");
    akdf::expand(changed, prk, 43, "TUNTOM-AKDF-v1-C2S", transcript);
    require(changed != c2s, "tunnel binding");
    for (std::size_t i = 0; i < dh.size(); ++i) {
        auto altered = dh; altered[i] ^= 1;
        akdf::extract(changed, psk, 42, altered);
        require(changed != prk, "full DH entropy input");
    }
    psk[0] ^= 1; akdf::extract(changed, psk, 42, dh);
    require(changed != prk, "PSK binding");
    std::array<std::uint8_t, 32> temporary; temporary.fill(42);
    try { WipeGuard wipe(temporary.data(), temporary.size()); throw 1; } catch (int) {}
    require(temporary == std::array<std::uint8_t,32>{}, "exception wipe");
    std::cout << "PASS: AKDF framing, domains, PSK/DH/transcript binding, exception wipe\n";
}
