#!/usr/bin/env python3
"""Extract SipHash-2-4 from Linux v6.12, using its BSD-3-Clause option.

Usage: python3 tools/extract_siphash.py DIRECTORY
DIRECTORY contains lib/siphash.c, include/linux/siphash.h, lib/siphash_kunit.c
and LICENSES/preferred/BSD-3-Clause downloaded under their base filenames.
No network or build-time dependency. This regenerates both vendored headers.
"""
import hashlib
from pathlib import Path
import re
import sys

HASHES = {
    'siphash.c': '0810315533525d0c25528a72a0c7a086b37fcdbb39b3460ab6bc85fe11778a10',
    'siphash.h': '180953494ea6728a626389d256f5fe2d44920c670353287e3644734c21766aa5',
    'siphash_kunit.c': 'f99b407f9d02ef4edda27600e0c153b06e3a440d09e1ceae0ca443872c2ac9e4',
    'BSD-3-Clause': '7a83b1aeb460458db9a4bd521d7f237c45b1650f6e60ea5ffc71e49472454de3',
}
sources = {}
for name, expected in HASHES.items():
    data = (Path(sys.argv[1]) / name).read_bytes()
    if hashlib.sha256(data).hexdigest() != expected:
        raise SystemExit('Not the pinned Linux v6.12 source: ' + name)
    sources[name] = data.decode()

copyright = 'Copyright (C) 2016-2022 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.'
license_text = sources['BSD-3-Clause'].split('License-Text:\n', 1)[1].strip()
license_text = license_text.replace('Copyright (c) <year> <owner> . All rights reserved.', copyright)
preamble = ('// Generated by tools/extract_siphash.py; do not edit.\n'
            '// Linux v6.12; SPDX-License-Identifier: BSD-3-Clause\n'
            + ''.join('// ' + name + ' SHA-256: ' + digest + '\n' for name, digest in HASHES.items())
            + '/*\n' + license_text + '\n*/\n#pragma once\n')
source = sources['siphash.c']
header = sources['siphash.h']
macros = header[header.index('#define SIPHASH_PERMUTATION'):header.index('#define HSIPHASH_PERMUTATION')]
macros += source[source.index('#define SIPROUND'):source.index('#ifndef CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS')]
generic = source[source.index('u64 __siphash_unaligned('):source.index('EXPORT_SYMBOL(__siphash_unaligned);')]
# Select the portable, bounded tail reads, excluding kernel word-access helpers.
generic = re.sub(r'#if defined\(CONFIG_DCACHE_WORD_ACCESS\).*?#else\n(.*?)#endif\n', r'\1', generic, flags=re.S)
generic = generic.replace('const void *data', 'const u8 *data')
generic = generic.replace('u64 __siphash_unaligned(', 'inline u64 siphash(')
generic = generic.replace('const u8 left = len & (sizeof(u64) - 1);',
                          'const u8 left = static_cast<u8>(len & (sizeof(u64) - 1));')
generic = generic.replace('fallthrough;', '[[fallthrough]];')
fixed = ''
for name in ('siphash_1u64', 'siphash_2u64'):
    function = source[source.index('u64 ' + name + '('):source.index('EXPORT_SYMBOL(' + name + ');')]
    fixed += 'inline ' + function
body = macros + generic + fixed
macro_names = re.findall(r'^#define (\w+)', macros, re.M)
for name in sorted(macro_names, key=len, reverse=True):
    body = re.sub(r'\b' + name + r'\b', 'TUNTOM_' + name, body)
helpers = '''#include <cstddef>
#include <cstdint>
namespace tuntom::linux_siphash {
using u8 = std::uint8_t;
using u64 = std::uint64_t;
using std::size_t;
struct siphash_key_t { u64 key[2]; };
inline u64 rol64(u64 value, unsigned count) {
    return (value << count) | (value >> (64 - count));
}
template <unsigned Bytes> inline u64 load_le(const u8 *data) {
    u64 value = 0;
    for (unsigned i = 0; i < Bytes; ++i) value |= u64(data[i]) << (8 * i);
    return value;
}
inline u64 get_unaligned_le64(const u8 *data) { return load_le<8>(data); }
inline u64 get_unaligned_le32(const u8 *data) { return load_le<4>(data); }
inline u64 get_unaligned_le16(const u8 *data) { return load_le<2>(data); }
'''
root = Path(__file__).resolve().parents[1]
(root / 'src/vendor/siphash.hpp').write_text(
    preamble + helpers + body + ''.join('#undef TUNTOM_' + name + '\n' for name in macro_names)
    + '} // namespace tuntom::linux_siphash\n')
vectors = re.search(r'static const u64 test_vectors_siphash\[64\] = \{(.*?)\};',
                    sources['siphash_kunit.c'], re.S).group(1)
(root / 'tests/siphash_vectors.hpp').write_text(
    preamble + '#include <cstdint>\ninline constexpr std::uint64_t siphash_vectors[64] = {'
    + vectors + '};\n')
