#!/usr/bin/env python3
"""Extract the pinned Monocypher 4.0.3 X25519 dependency closure.
Usage: python3 tools/extract_x25519.py /path/to/upstream/monocypher.c
No network or build-time dependencies. Output is committed in src/vendor/.
"""
import hashlib
import re
from pathlib import Path
import sys

source = Path(sys.argv[1]).read_bytes()
EXPECTED = 'f1f838cdd483bdebe0df0ff5c5ed60535e496f769c6a2f933ac4c0b114207123'
if hashlib.sha256(source).hexdigest() != EXPECTED:
    raise SystemExit('Not the pinned Monocypher 4.0.3 source')
lines = source.decode().splitlines()
ranges = [(1, 52), (63, 68), (73, 78), (92, 121), (144, 158),
          (161, 161), (164, 168), (931, 931), (943, 946),
          (971, 1357), (1370, 1594)]
license_text = '\n'.join(lines[:52])
body = '\n\n'.join('\n'.join(lines[a-1:b]) for a,b in ranges[1:])
# Only linkage changes: permit inclusion from multiple C++ translation units.
body = re.sub(r"^static ", "inline ", body, flags=re.MULTILINE)
for name in ('crypto_verify32', 'crypto_wipe', 'crypto_eddsa_trim_scalar',
             'crypto_x25519', 'crypto_x25519_public_key'):
    body = body.replace('int ' + name + '(', 'inline int ' + name + '(')
    body = body.replace('void ' + name + '(', 'inline void ' + name + '(')
header = ('// Generated by tools/extract_x25519.py; do not edit.\n'
          '// Monocypher 4.0.3, SHA-256: ' + EXPECTED + '\n'
          + license_text + '\n#pragma once\n#include <cstddef>\n#include <cstdint>\n'
          'namespace tuntom::monocypher {\n' + body + '\n'
          '#undef FOR_T\n#undef FOR\n#undef COPY\n#undef ZERO\n'
          '#undef WIPE_CTX\n#undef WIPE_BUFFER\n#undef FE_CARRY\n'
          '} // namespace tuntom::monocypher\n')
Path(__file__).resolve().parents[1].joinpath('src/vendor/x25519.hpp').write_text(header)
